pub const HTML_ELEMENTS: &[&str] = &[
    "<div>Hello World</div>",
    "<p>This is a paragraph</p>",
    "<span>Foo Bar</span>",
    "<h1>Heading 1</h1>",
    "<h2>Heading 2</h2>",
    "<a href='#'>Link Text</a>",
    "<strong>Bold Text</strong>",
    "<em>Italic Text</em>",
    "<u>Underlined Text</u>",
    "<s>Strikethrough Text</s>",
    "<code>Code Text</code>",
    "<blockquote>Blockquote Text</blockquote>",
    "<ul><li>Item 1</li><li>Item 2</li></ul>",
    "<ol><li>Item A</li><li>Item B</li></ol>",
    "<table><tr><td>Cell 1</td><td>Cell 2</td></tr></table>",
    "<img src='#' alt='Image Alt Text'/>",
    "<input type='text' value='Input Value'/>",
    "<button>Button Text</button>",
    "<select><option>Option 1</option><option>Option 2</option></select>",
    "<textarea>Textarea Text</textarea>",
];
